const {chromium}=require('playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const web=path.resolve(__dirname,'../ReflectionTimer.Desktop/Web');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});let passed=0;
  const check=(ok,name)=>{assert.ok(ok,name);passed++;console.log('PASS '+name);};
  try{
    const page=await browser.newPage({viewport:{width:940,height:780}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
    async function capture(name,target){if(process.env.REFLECTION_PREVIEW_SCREENSHOTS){await fs.mkdir(process.env.REFLECTION_PREVIEW_SCREENSHOTS,{recursive:true});await target.screenshot({path:path.join(process.env.REFLECTION_PREVIEW_SCREENSHOTS,name+'.png')});}}
    await page.route('**/*',async route=>{const name=path.basename(new URL(route.request().url()).pathname);if(!/\.(html|js|css)$/.test(name))return route.abort();await route.fulfill({body:await fs.readFile(path.join(web,name)),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html'});});
    await page.addInitScript(()=>{
      const handlers=[];window.messages=[];
      window.dispatchBridge=m=>handlers.forEach(h=>h({data:m}));
      window.settings={volume:50,tracks:[{id:0,name:'Default'},{id:6,name:'Battle (Trainer)'},{id:9,name:'None'}],sounds:[0,1,2,3,4,5].map(kind=>({kind,track:kind===5?6:0,behavior:kind===5?2:0,volume:100,fadeOutAfterSeconds:10,defaultName:'Battle (Trainer)'})),focusMode:{enabled:false,delaySeconds:5,target:null}};
      window.chrome={webview:{addEventListener:(_,h)=>handlers.push(h),postMessage:m=>{
        window.messages.push(m);queueMicrotask(()=>{
          if(m.action==='focusTargets')window.dispatchBridge({type:'focusTargets',kind:m.data.kind,targets:window.emptyTargets?[]:[{id:'target-a',name:m.data.kind===2?'Work group':m.data.kind===1?'Same tab title':'Work window',app:'chrome',windowName:'Browser window',tabPosition:1},{id:'target-b',name:m.data.kind===2?'Work group':'Same tab title',app:'chrome',windowName:'Browser window',tabPosition:2}].map(t=>({...t,selected:t.id===window.savedTargetId&&m.data.kind===window.settings.focusMode.targetKind}))});
          if(m.action==='focusSelect'){
            const kind=Number(document.querySelector('#focus-target-kind').value);
            const complete=()=>{
              if(window.selectionError){window.dispatchBridge({type:'reply',requestId:m.requestId,error:window.selectionError});return;}
              window.savedTargetId=m.data.id;window.settings.focusMode={...window.settings.focusMode,enabled:m.data.enable||window.settings.focusMode.enabled,target:kind===2?'Work group':kind===1?'Same tab title':m.data.id==='target-a'?'Work window':'Same tab title',targetKind:kind,targetApp:'chrome',targetWindowName:'Browser window',targetPosition:m.data.id==='target-a'?1:2};
              window.dispatchBridge({type:'settings',settings:window.settings});window.dispatchBridge({type:'reply',requestId:m.requestId});
            };
            if(window.holdSelection)window.releaseSelection=complete;else complete();return;
          }
          if(m.action==='focusMode'){window.settings.focusMode={...window.settings.focusMode,...m.data};window.dispatchBridge({type:'settings',settings:window.settings});}
          window.dispatchBridge({type:'reply',requestId:m.requestId});
        });
      }}};
    });
    await page.goto('https://reflection-timer.invalid/index.html?view=main');await page.waitForFunction(()=>window.messages.some(m=>m.action==='ready'));
    await page.evaluate(()=>window.dispatchBridge({type:'settings',settings:window.settings}));
    const pressed=()=>page.locator('#focus-enabled').getAttribute('aria-pressed');
    check(await pressed()==='false','Focus mode stays off for existing users');
    check(await page.locator('#choose-focus-target').textContent()==='Choose Window / Tab…'&&!await page.locator('#choose-focus-target').evaluate(el=>el.classList.contains('primary')),'No saved target uses the original selector label and inactive styling');
    check(await page.getByRole('checkbox',{name:'Focus mode',exact:true}).count()===0&&await page.getByRole('button',{name:'Focus',exact:true}).count()===1,'The Timer page uses a plain Focus toggle button without a checkbox');
    check(await page.locator('#focus-help').count()===0&&await page.locator('#focus-timer-options').count()===0,'The old Timer description and status block is removed');
    const buttonStyle=selector=>page.locator(selector).evaluate(el=>{const s=getComputedStyle(el);return {background:s.backgroundColor,color:s.color,padding:s.padding,borderRadius:s.borderRadius,height:el.getBoundingClientRect().height};});
    check(JSON.stringify(await buttonStyle('#focus-enabled'))===JSON.stringify(await buttonStyle('#reset')),'Inactive Focus has the same shape, size and colors as Reset');
    await page.setViewportSize({width:739,height:642});
    const inline=()=>page.evaluate(()=>{const r=document.querySelector('#reset').getBoundingClientRect(),f=document.querySelector('#focus-enabled').getBoundingClientRect(),c=document.querySelector('#choose-focus-target').getBoundingClientRect();return f.x>=r.right&&c.x>=f.right&&Math.abs(f.y+f.height/2-r.y-r.height/2)<1&&Math.abs(c.y+c.height/2-f.y-f.height/2)<1;});
    check(await inline(),'Focus and Choose window / tab sit immediately after Reset on one row at the original App width');
    await page.locator('#choose-focus-target').click();await page.locator('#focus-target-dialog').waitFor({state:'visible'});
    const pickerAligned=()=>page.evaluate(()=>{const s=document.querySelector('#focus-target-kind').getBoundingClientRect(),r=document.querySelector('#focus-target-refresh').getBoundingClientRect();return r.x>=s.right&&Math.abs(s.y+s.height/2-r.y-r.height/2)<1;});
    check(await pickerAligned(),'Refresh List aligns vertically with the target-type selector at the original App width');
    check(await page.getByRole('combobox',{name:'Target type',exact:true}).count()===1,'The target-type label remains associated after aligning the selector');
    check(await page.locator('#focus-target-kind option').allTextContents().then(labels=>JSON.stringify(labels)===JSON.stringify(['Window','Browser Tab','Browser Tab Groups'])),'The picker offers Window, Browser Tab and Browser Tab Groups with the requested casing');
    check(await page.locator('#focus-target-list option').allTextContents().then(labels=>labels[0]==='chrome · Work window'&&labels[1]==='chrome · Same tab title'),'Window listings begin with the app followed by its window title');
    await page.keyboard.press('Escape');await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(await page.locator('#choose-focus-target').evaluate(el=>el===document.activeElement)&&await pressed()==='false','Escape cancels target selection and restores focus without enabling monitoring');
    await page.locator('#focus-enabled').click();
    await page.getByRole('dialog',{name:'Choose a focus target'}).waitFor({state:'visible'});
    check(await page.locator('#focus-target-kind').evaluate(el=>el===document.activeElement),'Opening the selector focuses its labeled target-type control');
    await page.locator('#focus-target-use').click();await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(await pressed()==='true'&&await page.locator('#focus-enabled').evaluate(el=>el===document.activeElement),'Choosing a target enables focus mode and returns keyboard focus');
    check(await page.locator('#choose-focus-target .focus-target-type').textContent()==='Window'&&await page.locator('#choose-focus-target .focus-target-label').textContent()==='chrome · Work window'&&await page.locator('#choose-focus-target-settings .focus-target-label').textContent()==='chrome · Work window','Both target buttons put the saved window app first, just like its listing');
    check(await page.getByRole('button',{name:'Window: chrome · Work window',exact:true}).count()===1&&await page.locator('#choose-focus-target').getAttribute('aria-haspopup')==='dialog','The saved type and complete app/window name are accessible and identify the picker dialog');
    check(JSON.stringify(await buttonStyle('#focus-enabled'))===JSON.stringify(await buttonStyle('#toggle')),'Enabled Focus matches the Start button styling');
    check(await page.locator('#focus-enabled').textContent()==='Focus','The active button label remains Focus without On or Off text');
    await page.locator('#focus-enabled').press('Space');await page.waitForFunction(()=>document.querySelector('#focus-enabled').getAttribute('aria-pressed')==='false');
    check(await page.evaluate(()=>window.settings.focusMode.target==='Work window'&&window.savedTargetId==='target-a'),'Turning Focus off retains the chosen target');
    check(await page.locator('#choose-focus-target').evaluate(el=>el.classList.contains('primary'))&&await page.locator('#choose-focus-target-settings').evaluate(el=>el.classList.contains('primary')),'Saved target buttons stay highlighted independently of the Focus toggle');
    await page.locator('#focus-enabled').press('Enter');await page.waitForFunction(()=>document.querySelector('#focus-enabled').getAttribute('aria-pressed')==='true');
    check(!await page.evaluate(()=>window.messages.some(m=>m.action==='toggle')),'Enter and Space toggle Focus without starting or pausing the timer');
    check(await page.evaluate(()=>window.messages.filter(m=>m.action==='focusSelect').at(-1).data.id==='target-a'),'Only the native listed target ID crosses the selection bridge');
    await page.locator('#session-mode').click();
    await page.evaluate(()=>window.dispatchBridge({type:'state',state:{clock:{seconds:0,text:'0 seconds',status:'Ready',stopwatch:true},timer:{mode:1,durationSeconds:900,autoRestart:false,enabled:false,threshold:15},prompts:[],schedules:[],outbox:[],focusMode:window.settings.focusMode}}));
    check(await page.locator('#focus-enabled').isVisible()&&await pressed()==='true'&&await page.locator('#session-mode').textContent().then(text=>text.includes('Stopwatch')),'The selected focus target and toggle remain available in Stopwatch mode');
    check(await inline(),'The same Reset, Focus and target-selector row is retained in Stopwatch mode');
    await capture('focus-stopwatch',page.locator('body'));
    await page.locator('#tab-settings').click();
    check(await page.locator('#sound-form-5 legend').textContent()==='Focus mode · away from selected window or tab','Focus audio has a matching independent settings section');
    check(await page.locator('#sound-track-5').inputValue()==='6','Default focus selection is Battle (Trainer)');
    check(await page.locator('#sound-message-fade-row-5').count()===0,'Focus audio does not expose irrelevant message-sent fade options');
    await page.locator('#focus-delay').fill('8');await page.locator('#focus-audio-help').click();
    await page.waitForFunction(()=>window.messages.some(m=>m.action==='focusMode'&&m.data.delaySeconds===8));
    check(!await page.evaluate(()=>window.messages.some(m=>m.action==='saveSound')),'Focus delay autosaves without overwriting sound settings');
    await page.locator('#choose-focus-target-settings').click();await page.locator('#focus-target-kind').selectOption('1');
    await page.waitForFunction(()=>window.messages.some(m=>m.action==='focusTargets'&&m.data.kind===1));
    check(await page.locator('#focus-target-list option').allTextContents().then(labels=>labels[0]==='chrome · Browser window — Same tab title · Tab 1'&&labels[1]==='chrome · Browser window — Same tab title · Tab 2'),'Browser-tab listings place the app and window before the tab name and position');
    await page.locator('#focus-target-list').selectOption('target-b');await page.locator('#focus-target-use').click();
    await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(await page.evaluate(()=>window.messages.filter(m=>m.action==='focusSelect').at(-1).data.id==='target-b'),'Duplicate tab titles remain separately selectable by stable IDs');
    await page.locator('#focus-settings-enabled').click();
    await page.waitForFunction(()=>window.messages.some(m=>m.action==='focusMode'&&!m.data.enabled));
    check(await pressed()==='false'&&await page.locator('#focus-settings-enabled').getAttribute('aria-pressed')==='false','Audio settings and Timer toggle buttons stay synchronized');
    await page.locator('#choose-focus-target-settings').click();await page.locator('#focus-target-list').waitFor({state:'visible'});
    await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    check(await page.locator('#focus-target-list').inputValue()==='target-b','The previously chosen tab is preselected when reopening the picker while Focus is off');
    await page.locator('#focus-target-use').click();await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(await pressed()==='false','Choosing or confirming a target does not turn Focus on unless its toggle requested it');
    await page.locator('#choose-focus-target-settings').click();await page.locator('#focus-target-kind').selectOption('2');
    await page.waitForFunction(()=>document.querySelector('#focus-target-list option')?.textContent.endsWith('Group 1'));
    check(await page.locator('#focus-target-list option').allTextContents().then(labels=>labels.length===2&&labels[0]==='chrome · Browser window — Work group · Group 1'&&labels[1]==='chrome · Browser window — Work group · Group 2'),'Browser-group listings place the app and window first while preserving distinct group positions');
    await page.locator('#focus-target-list').selectOption('target-b');await page.locator('#focus-target-use').click();await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(await page.evaluate(()=>window.settings.focusMode.targetKind===2&&window.savedTargetId==='target-b')&&await page.locator('#focus-settings-target').textContent()==='Tab Group: chrome · Browser window — Work group · Group 2','Choosing a group saves its native ID and exposes the correct accessible summary');
    await page.locator('#choose-focus-target-settings').click();await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    check(await page.locator('#focus-target-kind').inputValue()==='2'&&await page.locator('#focus-target-list').inputValue()==='target-b','Reopening the picker preserves the saved group type and exact group selection');
    await page.evaluate(()=>window.emptyTargets=true);await page.locator('#focus-target-refresh').click();
    await page.waitForFunction(()=>document.querySelector('#focus-picker-status').textContent.startsWith('No readable browser tab groups'));
    check(await page.locator('#focus-target-list').isDisabled()&&await page.locator('#focus-target-use').isDisabled(),'An unavailable group list cannot save a stale target');
    await page.evaluate(()=>window.emptyTargets=false);await page.locator('#focus-target-refresh').click();await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    check(await page.locator('#focus-target-list').inputValue()==='target-b','Refresh List restores a still-available saved group without changing it');
    await page.locator('#focus-target-cancel').click();
    const selectionCount=()=>page.evaluate(()=>window.messages.filter(m=>m.action==='focusSelect').length);
    const unrelatedCount=()=>page.evaluate(()=>window.messages.filter(m=>['toggle','settingsSaveComplete'].includes(m.action)).length);
    for(const [kind,gesture,prefix] of [['0','Enter','Window'],['1','Space','Tab'],['2','Double-click','Tab Group']]){
      await page.locator('#choose-focus-target-settings').click();await page.locator('#focus-target-kind').selectOption(kind);
      await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
      await page.locator('#focus-target-list').selectOption('target-b');
      const listedName=await page.locator('#focus-target-list option[value="target-b"]').textContent();
      const count=await selectionCount(),unrelated=await unrelatedCount();
      if(gesture==='Double-click')await page.locator('#focus-target-list option[value="target-b"]').dblclick();
      else await page.locator('#focus-target-list').press(gesture);
      await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
      check(await selectionCount()===count+1&&await page.evaluate(kind=>window.savedTargetId==='target-b'&&window.settings.focusMode.targetKind===Number(kind),kind),gesture+' confirms the selected '+prefix.toLowerCase()+' through the same save action');
      check(await page.locator('#choose-focus-target-settings .focus-target-type').textContent()===prefix&&await page.locator('#choose-focus-target-settings .focus-target-label').textContent()===listedName&&await page.locator('#choose-focus-target-settings').evaluate(el=>el===document.activeElement),'Confirming a '+prefix.toLowerCase()+' uses the exact app/window-first listing name and restores opener focus');
      check(await unrelatedCount()===unrelated&&await pressed()==='false',gesture+' in the picker does not start the timer, save unrelated settings, or enable Focus');
    }
    await page.locator('#choose-focus-target-settings').click();await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    let count=await selectionCount();
    await page.locator('#focus-target-list').press('Control+Enter');await page.locator('#focus-target-list').press('Control+Space');
    check(await page.locator('#focus-target-dialog').isVisible()&&await selectionCount()===count,'Modified Enter and Space retain their shortcuts and do not confirm a target');
    await page.locator('#focus-target-list').press('ArrowUp');
    check(await page.locator('#focus-target-list').inputValue()==='target-a'&&await page.locator('#focus-target-dialog').isVisible(),'Arrow keys navigate the list without confirming a target');
    await page.locator('#focus-target-list').focus();await page.keyboard.down('Space');await page.keyboard.down('Space');
    check(await page.locator('#focus-target-dialog').isVisible()&&await selectionCount()===count,'Holding Space waits for release instead of saving repeatedly');
    await page.keyboard.up('Space');await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(await selectionCount()===count+1,'Space confirms once on release without reopening the picker');
    await page.locator('#choose-focus-target-settings').click();await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    count=await selectionCount();await page.locator('#focus-target-list').focus();await page.keyboard.down('Enter');
    await page.locator('#focus-target-dialog').waitFor({state:'hidden'});await page.keyboard.down('Enter');await page.keyboard.up('Enter');
    check(await selectionCount()===count+1&&!await page.locator('#focus-target-dialog').isVisible(),'Holding Enter confirms once and does not reopen the picker after focus returns');
    await page.locator('#choose-focus-target-settings').click();await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    await page.evaluate(()=>window.holdSelection=true);count=await selectionCount();await page.locator('#focus-target-list').press('Enter');
    await page.waitForFunction(()=>document.querySelector('#focus-target-dialog').getAttribute('aria-busy')==='true');
    check(await page.locator('#focus-target-list').isDisabled()&&await page.locator('#focus-target-kind').isDisabled()&&await page.locator('#focus-target-refresh').isDisabled(),'Saving temporarily prevents changing or refreshing the target behind an in-flight selection');
    await page.evaluate(()=>{const list=document.querySelector('#focus-target-list');list.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));list.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));});
    check(await selectionCount()===count+1,'Overlapping keyboard and double-click events cannot send duplicate selection requests');
    await page.evaluate(()=>{window.holdSelection=false;window.releaseSelection();});await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    await page.locator('#choose-focus-target-settings').click();await page.waitForFunction(()=>!document.querySelector('#focus-target-list').disabled);
    await page.evaluate(()=>window.selectionError='That target closed. Refresh and choose again.');await page.locator('#focus-target-list').press('Enter');
    await page.waitForFunction(()=>document.querySelector('#focus-picker-status').textContent.includes('That target closed'));
    check(await page.locator('#focus-target-dialog').isVisible()&&!await page.locator('#focus-target-list').isDisabled()&&!await page.locator('#focus-target-use').isDisabled()&&await page.locator('#focus-target-list').evaluate(el=>el===document.activeElement),'A failed selection stays readable inside the dialog and restores the list for retry');
    await page.evaluate(()=>window.selectionError=null);await page.locator('#focus-target-list').press('Enter');await page.locator('#focus-target-dialog').waitFor({state:'hidden'});
    check(!await page.locator('#focus-target-dialog').isVisible(),'Keyboard confirmation works again after an unsuccessful save');
    await page.locator('#focus-delay').fill('12');await page.locator('#focus-delay').press('Control+s');
    await page.waitForFunction(()=>window.messages.some(m=>m.action==='settingsSaveComplete'));
    check(await page.evaluate(()=>window.messages.filter(m=>m.action==='focusMode').at(-1).data.delaySeconds===12),'Ctrl+S flushes an unblurred focus delay edit');
    await page.locator('#focus-delay').fill('-1');await page.locator('#focus-audio-help').click();
    check(!await page.locator('#focus-delay').evaluate(el=>el.checkValidity()),'Invalid negative delays are rejected');
    await page.locator('#focus-delay').fill('5');await page.locator('#focus-audio-help').click();
    await page.locator('#sound-track-5').selectOption('9');
    await page.waitForFunction(()=>window.messages.some(m=>m.action==='saveSound'&&m.data.kind===5));
    check(await page.evaluate(()=>window.messages.filter(m=>m.action==='saveSound').at(-1).data.track===9),'Focus audio can independently be set to None');
    for(const theme of [0,1,2,3]){
      await page.evaluate(theme=>window.dispatchBridge({type:'settings',settings:{...window.settings,theme}}),theme);
      const centered=await page.locator('#focus-delay').evaluate(input=>{const r=input.getBoundingClientRect(),label=input.previousElementSibling.getBoundingClientRect();return Math.abs(r.y+r.height/2-label.y-label.height/2)<2;});
      check(centered,'Delay row is vertically centered in theme '+theme);
      const offStyle=await buttonStyle('#focus-settings-enabled');await page.locator('#focus-settings-enabled').click();
      const onStyle=await buttonStyle('#focus-settings-enabled'),startStyle=await buttonStyle('#toggle');
      check(onStyle.background===startStyle.background&&onStyle.color===startStyle.color&&offStyle.padding===onStyle.padding&&await page.locator('#focus-settings-enabled').textContent()==='Focus','Focus changes only its active styling and keeps its label and size in theme '+theme);
      await page.locator('#focus-settings-enabled').click();
      const targetStyle=await buttonStyle('#choose-focus-target-settings');
      check(targetStyle.background===startStyle.background&&targetStyle.color===startStyle.color,'Saved target styling matches enabled Focus in theme '+theme+' even with Focus off');
      check(await page.locator('#choose-focus-target-settings').evaluate(el=>{const type=el.querySelector('.focus-target-type'),name=el.querySelector('.focus-target-label');return Number(getComputedStyle(type).fontWeight)>=700&&type.getBoundingClientRect().bottom<=name.getBoundingClientRect().top&&getComputedStyle(name).fontWeight==='400';}),'The target type is bold above its regular name in theme '+theme);
      await capture('focus-audio-theme-'+theme,page.locator('#sound-form-5'));
      await page.locator('#choose-focus-target-settings').click();await page.locator('#focus-target-dialog').waitFor({state:'visible'});
      check(await pickerAligned(),'Refresh List is vertically aligned with its selector in theme '+theme);
      await page.locator('#focus-target-cancel').click();
    }
    await page.locator('#choose-focus-target-settings').click();await page.locator('#focus-target-dialog').waitFor({state:'visible'});
    await capture('focus-target-selector',page.locator('#focus-target-dialog'));
    await page.locator('#focus-target-cancel').click();
    const longName='A long saved browser tab name '.repeat(15);
    await page.evaluate(name=>{window.settings.focusMode={...window.settings.focusMode,target:name,targetKind:1,targetApp:'chrome',targetWindowName:'Browser window',targetPosition:2,enabled:false};window.dispatchBridge({type:'settings',settings:window.settings});},longName);
    await page.locator('#tab-timer').click();
    check(await inline()&&await page.locator('#choose-focus-target').evaluate(el=>{const name=el.querySelector('.focus-target-label');return el.getBoundingClientRect().width<=260&&name.scrollWidth>name.clientWidth;}),'Long saved target names are visually shortened without stretching or wrapping the original action row');
    check(await page.locator('#choose-focus-target').getAttribute('aria-label')==='Tab: chrome · Browser window — '+longName+' · Tab 2'&&await page.locator('#choose-focus-target').getAttribute('title').then(title=>title.includes(longName)),'Screen readers and the hover tooltip retain the full saved app/window-first target name');
    await capture('saved-focus-target',page.locator('#timer-editor > .actions'));
    await page.evaluate(()=>{window.settings.focusMode={enabled:false,delaySeconds:5,target:'Already saved document - Excel',targetKind:0,targetApp:'EXCEL'};window.dispatchBridge({type:'settings',settings:window.settings});});
    check(await page.locator('#choose-focus-target .focus-target-label').textContent()==='EXCEL · Already saved document - Excel','An existing saved window displays its app first without choosing it again or needing newer window metadata');
    await capture('saved-window-focus-target',page.locator('#timer-editor > .actions'));
    await page.evaluate(()=>{window.dispatchBridge({type:'state',state:{clock:{seconds:0,text:'0 seconds',status:'Ready',stopwatch:true},timer:{mode:1,durationSeconds:900,autoRestart:false,enabled:false,threshold:15},prompts:[],schedules:[],outbox:[],focusMode:{...window.settings.focusMode,target:'Updated window title'}}});});
    check(await page.locator('#choose-focus-target .focus-target-label').textContent()==='EXCEL · Updated window title'&&await page.locator('#choose-focus-target .focus-target-type').count()===1,'Timer state refreshes retain the two-line display without duplicating its heading');
    await page.evaluate(()=>window.dispatchBridge({type:'settings',settings:{...window.settings,focusMode:{enabled:false,delaySeconds:5,target:null}}}));
    check(await page.locator('#choose-focus-target').textContent()==='Choose Window / Tab…'&&await page.locator('#choose-focus-target .focus-target-type').count()===0&&!await page.locator('#choose-focus-target').getAttribute('aria-label')&&!await page.locator('#choose-focus-target').evaluate(el=>el.classList.contains('primary')||el.classList.contains('has-target')),'Clearing a saved target restores the original chooser name and styling');
    check(errors.length===0,'Focus controls have no browser script errors');
    console.log(`${passed} focus browser checks passed.`);
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
